blank_issues_enabled: false
contact_links:
  - name: VI Software Documentation
    url: https://docs.visoftware.dev/vi-software/vis-launcher
    about: Check our documentation for answers to common questions
  - name: VIS Launcher Discord Community
    url: https://visoftware.dev/discord
    about: Join our Discord server to get help from the community
  - name: Security Issues
    url: https://github.com/VI-Software/vis-launcher/security/policy
    about: Please report security vulnerabilities here instead of opening a public issue