#
#    ____   ____.___    _________       _____  __                                 
# \   \ /   /|   |  /   _____/ _____/ ____\/  |___  _  _______ _______   ____  
#  \   Y   / |   |  \_____  \ /  _ \   __\\   __\ \/ \/ /\__  \\_  __ \_/ __ \ 
#  \     /  |   |  /        (  <_> )  |   |  |  \     /  / __ \|  | \/\  ___/ 
#   \___/   |___| /_______  /\____/|__|   |__|   \/\_/  (____  /__|    \___  >
#                         \/                                 \/            \/ 
#                         
#                         
#    Copyright 2024 (©) VI Software y contribuidores. Todos los derechos reservados.
#    
#    GitHub: https://github.com/VI-Software
#    Documentación: https://docs.visoftware.tech/vi-software/vis-launcher
#    Web: https://visoftware.tech
#    Licencia del proyecto: https://github.com/VI-Software/vis-launcher/blob/main/LICENSE

[ejs.landing]
updateAvailableTooltip = "Actualización disponible"
usernamePlaceholder = "Nombre de usuario"
usernameEditButton = "Editar"
settingsTooltip = "Configuración"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "DESCONECTADO"
mojangStatus = "ESTADO DE MOJANG"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;Esenciales"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "&#8226; Ningún servidor seleccionado"
launchDetails = "Por favor espera.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Verificando noticias.."
newsErrorFailedSpan = "Error al cargar noticias"
newsErrorRetryButton = "Intentar de nuevo"
newsErrorNoneSpan = "Sin noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "Iniciando sesión con VI Software Yggdrasil"
loginEmailError = "* Valor Inválido"
loginEmailPlaceholder = "NOMBRE DE USUARIO"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://docs.visoftware.tech/vi-software/vis-yggdrasil-auth/ver-la-informacion-de-mi-cuenta"
loginForgotPasswordText = "Consultar tus datos"
loginRememberMeText = "Recuérdame"
loginButtonText = "INICIAR SESIÓN"
loginNeedAccountLink = "https://puf.visoftware.tech"
loginNeedAccountText = "¿Necesitas una cuenta?"
loginPasswordDisclaimer1 = "Tu contraseña se envía directamente al servidor de VI Software y nunca se almacena."
loginPasswordDisclaimer2 = "&copy 2024 VI Software y contribuidores. Todos los derechos reservados."

[ejs.loginOptions]
loginOptionsTitle = "Opciones de inicio de sesión"
loginWithMicrosoft = "Iniciar sesión con Microsoft"
loginWithVIS = "Iniciar sesión con VI Software"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecciona una cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuración"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Hecho"
tabAccountHeaderText = "Configuración de la Cuenta"
tabAccountHeaderDesc = "Añade nuevas cuentas o gestiona las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Añadir Cuenta de Microsoft"
VISAccount = "VI Software"
addVISAccount = "+ Añadir Cuenta de VI Software"
minecraftTabHeaderText = "Configuración de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resolución del juego"
launchFullscreenTitle = "Iniciar en pantalla completa."
autoConnectTitle = "Automáticamente conectar al servidor al lanzar el juego si disponible."
autoConnectDesc = "Se conecta automáticamente al servidor si la funcionalidad está disponible en el servidor seleccionado. (Debe de haber sido activado por la administradora de la experiencia)"
launchDetachedTitle = "(Avanzado) Separar el proceso del juego respecto al proceso del launcher"
launchDetachedDesc = "Si los procesos del launcher y el juego no están separados, cerrar el launcher supondrá que el juego también se cierre."
tabModsHeaderText = "Configuración de Mods"
tabModsHeaderDesc = "Habilita o deshabilita mods."
switchServerButton = "Cambiar"
requiredMods = "Mods Obligatorios"
optionalMods = "Mods Opcionales"
dropinMods = "Mods Drop-in"
addMods = "Añadir Mods"
dropinRefreshNote = "(F5 para Actualizar)"
shaderpacks = "Paquetes de Shaders"
shaderpackDesc = "Habilita o deshabilita shaders. Ten en cuenta que los shaders solo se ejecutarán sin problemas en configuraciones potentes. Puedes añadir paquetes personalizados aquí."
selectShaderpack = "Seleccionar Paquete de Shaders"
tabJavaHeaderText = "Configuración de Java"
tabJavaHeaderDesc = "Gestiona la configuración avanzada de Java."
memoryTitle = "Memoria"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "Se recomienda un mínimo de 3 gigabytes de RAM. Establecer los valores mínimo y máximo en el mismo valor puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar ejecutable de Java"
javaExecSelButtonText = "Elegir archivo"
javaExecDesc = "El ejecutable de Java se valida antes del inicio del juego."
javaPathDesc = "La ruta debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones Adicionales de JVM"
jvmOptsDesc = "Opciones que se proporcionarán a la JVM en tiempo de ejecución. <em>-Xms</em> y <em>-Xmx</em> no deben incluirse."
launcherTabHeaderText = "Configuración del launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el launcher en sí."
allowPrereleaseTitle = "Canal de actualizaciones nightly."
allowPrereleaseDesc = "Las versiones nightly incluyen nuevas funciones que pueden no haber sido completamente probadas o integradas.<br>Esta opción será considerada como activa siempre que se esté en una versión nightly."
dataDirectoryTitle = "Directorio de Datos"
selectDataDirectory = "Seleccionar Directorio de Datos"
chooseFolder = "Elegir Carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java se almacenarán en el directorio de datos.<br>Las capturas de pantalla y los guardados de mundos se almacenan en la carpeta de instancia para la configuración de servidor correspondiente."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver información y notas de lanzamiento de la versión actual."
aboutTitle = "{appName}"
stableRelease = "Versión Estable"
versionText = "Versión "
sourceGithub = "Fuente (GitHub)"
soporte = "Soporte"
devToolsConsole = "Consola de Herramientas de desarrollo"
releaseNotes = "Notas de lanzamiento"
changelog = "Registro de cambios"
noReleaseNotes = "Sin notas de lanzamiento"
viewReleaseNotes = "Ver Notas de lanzamiento en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del launcher"
launcherUpdatesHeaderDesc = "Descarga, instala y revisa las actualizaciones del launcher."
checkForUpdates = "Buscar actualizaciones"
whatsNew = "¿Qué hay de nuevo?"
updateReleaseNotes = "Notas de lanzamiento de la actualización"

[ejs.waiting]
waitingText = "Esperando a Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.discord]
waiting = "Esperando al cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de sesión de Microsoft"
microsoftLogoutTitle = "Cierre de sesión de Microsoft"

[js.login]
login = "INICIAR SESIÓN"
loggingIn = "INICIANDO SESIÓN"
success = "ÉXITO"
tryAgain = "Intentar de Nuevo"

[js.login.error]
invalidValue = "* Valor Inválido"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Error desconocido durante el inicio de sesión"
desc = "Ha ocurrido un error desconocido. Consulta la consola para obtener más detalles (CTRL + Shift + i)"

[js.landing.launch]
pleaseWait = "Por favor espera..."
checkingClient = "Verificando instancia..."
checkingAccount = "Autentificando..."
failureTitle = "Error durante el lanzamiento"
failureText = "Consulta la consola (CTRL + Shift + i) para obtener más detalles."
noaccessTitle = "Error durante el lanzamiento"
noaccessText = "La cuenta seleccionada no tiene permiso para acceder al servidor seleccionado."
NoCheckModErrorTitle = "Error durante el lanzamiento"
NoCheckModErrorText = "No se ha podido verificar la cuenta en el sistema de moderación de VI Software. <br>Consulta la consola (CTRL + Shift + i) para obtener más detalles."
WarnsnotreadErrorTitle = "Error durante el lanzamiento"
WarnsnotreadErrorText = 'Hay una o más sanciones a la espera de que sean vistas por ti. <a href="https://puf.visoftware.tech" style="color: red">Puedes consultarlas en el panel de usuario final de VI Software</a>'
AccountDisabledErrorTitle = "Error durante el lanzamiento"
AccountDisabledErrorText = 'La cuenta seleccionada se encuentra actualmente deshabilitada <span style="color: pink;">por la administradora de la experiencia</span>. Puede consultar más información sobre sus cuentas en <a href="https://puf.visoftware.tech" style="color: pink;">el panel de usuario final de VI Software</a>. <br>VI Software <span style="color: red";>NO</span> puede asistirle con este asunto.'
TeamBannedErrorTitle = "Error durante el lanzamiento"
TeamBannedErrorText = 'El Team propietario del servidor se encuentra actualmente suspendido <span style="color: pink;">por VI Software</span>. <br>Esto es una sanción impuesta al Team propietario del servidor, no a su cuenta.'
GlobalAccountDisabledErrorTitle = "401 | Unauthorized"
GlobalAccountDisabledErrorText = 'No tiene suficientes permisos para acceder al recurso solicitado. <br> Consulta la consola para obtener más detalles (CTRL + Shift + i)'
ErrorCantCheckTeamOnApiErrorTitle = "Error durante el lanzamiento"
ErrorCantCheckTeamOnApiErrorText = "No hemos podido verificar el estado de actividad del Team del servidor. <br>Consulta la consola (CTRL + Shift + i) para obtener más detalles."
serverNotFoundErrorTitle="Error durante el lanzamiento"
serverNotFoundErrorText="No se ha podido encontrar el servidor seleccionado para la cuenta selecionada. <br>Consulta la consola (CTRL + Shift + i) para obtener más detalles."
okay = "Aceptar"

[js.landing.selectedAccount]
noAccountSelected = "Ninguna cuenta seleccionada"

[js.landing.selectedServer]
noSelection = "Ningún servidor seleccionado"
loading = "Cargando..."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "DESCONECTADO"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Verificando información del sistema.."
noCompatibleJava = "No se encontró una instalación compatible de Java."
installJavaMessage = "Para iniciar Minecraft, necesitas una instalación de 64 bits de Java {major}. ¿Quieres que instalemos una copia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando descarga de Java.."
javaDownloadFailureTitle = "Error durante la descarga de Java"
javaDownloadFailureText = "Consulta la consola (CTRL + Shift + i) para obtener más detalles."
javaRequired = "Java es Requerido<br>para iniciar"
javaRequiredMessage = 'Se requiere una instalación válida de x64 de Java {major} para iniciar.<br><br>Consulta esta <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guía de Gestión de Java</a> para obtener instrucciones sobre cómo instalar Java manualmente.'
javaRequiredDismiss = "Entiendo"
javaRequiredCancel = "Volver atrás"

[js.landing.downloadJava]
findJdkFailure = "No se pudo encontrar una distribución de OpenJDK."
javaDownloadCorruptedError = "El JDK descargado tiene un hash incorrecto, es posible que el archivo esté dañado."
extractingJava = "Extrayendo Java"
javaInstalled = "¡Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Cargando información..."
fatalError = "Error fatal"
unableToLoadDistributionIndex = "No se pudo cargar una copia del índice de distribución. Consulta la consola (CTRL + Shift + i) para obtener más detalles."
pleaseWait = "Por favor espera..."
errorDuringLaunchTitle = "Error durante el lanzamiento"
seeConsoleForDetails = "Consulta la consola (CTRL + Shift + i) para obtener más detalles."
validatingFileIntegrity = "Validando archivos..."
errorDuringFileVerificationTitle = "Error durante la verificación del archivo"
downloadingFiles = "Descargando archivos..."
errorDuringFileDownloadTitle = "Error durante la descarga del archivo"
preparingToLaunch = "Preparando para lanzar..."
launchingGame = "Iniciando juego..."
launchWrapperNotDownloaded = "El archivo principal, LaunchWrapper, no se descargó correctamente. Como resultado, el juego no puede iniciarse.<br><br>Para solucionar este problema, desactiva temporalmente tu software antivirus y vuelve a iniciar el juego.<br><br>Si tienes tiempo, por favor <a href=\"https://github.com/VI-Software/vis-launcher/issues\">abre una issue en nuestro github</a> y avísanos qué software antivirus estás utilizando. Nos pondremos en contacto con ellos y trataremos de solucionar las cosas."
doneEnjoyServer = "Listo. ¡Disfruta del servidor!"
checkConsoleForDetails = "Por favor, revisa la consola (CTRL + Shift + i) para obtener más detalles."

[js.landing.news]
checking = "Verificando noticias..."

[js.landing.discord]
loading = "Cargando juego..."
joining = "Conectado con el servidor..."
joined = "En un servidor multijugador"

[js.overlay]
dismiss = "Descartar"

[js.settings.fileSelectors]
executables = "Ejecutables"
allFiles = "Todos los archivos"

[js.settings.mstfLogin]
errorTitle = "Algo salió mal"
errorMessage = "La autenticación de Microsoft falló. Por favor, inténtalo de nuevo."
okButton = "Aceptar"

[js.settings.mstfLogout]
errorTitle = "Algo salió mal"
errorMessage = "La desconexión de Microsoft falló. Por favor, inténtalo de nuevo."
okButton = "Aceptar"

[js.settings.authAccountSelect]
selectButton = "Seleccionar Cuenta"
selectedButton = "Cuenta Seleccionada ✓"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Advertencia<br>Esta es tu última cuenta"
lastAccountWarningMessage = "Para usar el launcher, debes estar conectado al menos a una cuenta. Necesitarás iniciar sesión nuevamente después.<br><br>¿Estás seguro/a de que quieres cerrar sesión?"
confirmButton = "Estoy Seguro/a"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nombre de usuario"
rank = "Rango"
uuid = "UUID"
selectAccount = "Seleccionar Cuenta"
selectedAccount = "Cuenta Seleccionada ✓"
logout = "Cerrar Sesión"

[js.settings.dropinMods]
removeButton = "Eliminar"
deleteFailedTitle = "Error al eliminar<br>mod drop-in {fullName}"
deleteFailedMessage = "Asegúrate de que el archivo no esté en uso y vuelve a intentarlo."
failedToggleTitle = "Error al aaternar<br>Uno o más mods drop-in"
okButton = "Aceptar"

[js.settings.serverListing]
mainServer = "Servidor Principal"
info = 'Puedes gestionar tus servidores en <a style="color: pink;" href="https://puf.visoftware.tech/servers">https://puf.visoftware.tech/servers</a>.</div>'
noServers = 'No tenemos servidores para mostrarte. <br>Puedes gestionar los servidores que aparecen aquí en el <a style="color: pink;" href="https://puf.visoftware.tech/servers">panel de usuario final de VI Software</a>.</div>'

[js.settings.java]
selectedJava = "Seleccionado: Java {version} ({vendor})"
invalidSelection = "Selección inválida"
requiresJava = "Requiere Java {major} x64."
availableOptions = "Opciones disponibles para Java {major} (VM HotSpot)"

[js.settings.about]
preReleaseTitle = "Versión nightly"
stableReleaseTitle = "Versión estable"
releaseNotesFailed = "Error al cargar las notas de la versión."

[js.settings.updates]
newReleaseTitle = "Nueva versión disponible"
newPreReleaseTitle = "Nueva versión de prenlanzamiento disponible"
downloadingButton = "Descargando..."
downloadButton = 'Descargar desde GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Cierra el launcher y ejecuta el archivo dmg para actualizar.</span>'
latestVersionTitle = "Estás utilizando la última versión"
checkForUpdatesButton = "Buscar actualizaciones"
checkingForUpdatesButton = "Buscando actualizaciones..."

[js.uibinder.startup]
fatalErrorTitle = "Error Fatal: No se puede cargar el índice de distribución"
fatalErrorMessage = "No se pudo establecer una conexión con nuestros servidores para descargar el índice de distribución. No había copias locales disponibles para cargar. <br><br>El índice de distribución es un archivo esencial que proporciona la información más reciente del servidor. El launcher no puede iniciarse sin él. Asegúrate de estar conectado a Internet y vuelve a iniciar la aplicación."
closeButton = "Cerrar"

[js.landing.forceupdate]
forceupdateErrorTitle = "Versión no soportada"
forceupdateErrorMessage = 'La versión actual del launcher no está soportada y VI Software ha ordenado la migración a una versión más reciente, preferiblemente mantenida. Puede descargar la última versión estable <a href="https://github.com/VI-Software/vis-launcher/releases/latest" style="color: red">aquí</a>.'
closeButton = "De acuerdo"

[js.landing.unmantained]
unmantainedErrorTitle = "Versión no mantenida"
unmantainedErrorMessage = 'Estás utilizando una versión desactualizada de VI Software Launcher, esta ya no está mantenida por VI Software y no ofrece soporte. Las nuevas versiones pueden traer nuevas características, solución de bugs y parches para las vulnerabilidades. Es importante mantenerse con la última versión estable. Puede descargar la última versión estable <a href="https://github.com/VI-Software/vis-launcher/releases/latest" style="color: red">aquí</a>'

[js.uibinder.bgservicewarning]
bgservicewarningErrorTitle = "Ha ocurrido un error"
bgservicewarningErrorMessage = 'Ha ocurrido un error al intentar conectarse a VI Software Background Services. Como resultado, no hemos podido cargar un fondo dinámico. Hemos aplicado un fondo offline estático, esto puede deberse a un incidente en la infraestructura del servicio, pero si no hay un incidente comunicado, esto podría ser un problema en su final. Puede encontrar más información respecto a este error <a href="https://docs.visoftware.tech/vi-software/vis-launcher/error-al-intentar-conectarse-a-vi-software-background-services" style="color: red">aquí</a>'
ignoreButton = "Continuar"

[js.uibinder.fatalapierror]
fatalapierrorErrorTitle = "Error catastrófico"
fatalapierrorErrorMessage = 'No se ha podido conectar al API de VI Software. No podemos continuar de ninguna manera. Si no hay ninguna incidencia por parte de VI Software, podría ser un problema en su final. Puede encontrar más información <a href="https://github.com/VI-Software/vis-launcher/releases/latest" style="color: red">aquí</a>'
closeButton = "Cerrar"

[js.uibinder.validateAccount]
failedMessageTitle = "Error al actualizar el inicio de sesión"
failedMessage = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, selecciona otra cuenta o inicia sesión nuevamente."
failedMessageSelectAnotherAccount = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, inicia sesión nuevamente."
loginButton = "Iniciar sesión"
selectAnotherAccountButton = "Seleccionar otra cuenta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando actualizaciones..."
installNowButton = "Instalar ahora"
checkForUpdatesButton = "Buscar actualizaciones"

