# ____   ____.___    _________       _____  __                                 
# \   \ /   /|   |  /   _____/ _____/ ____\/  |___  _  _______ _______   ____  
#  \   Y   / |   |  \_____  \ /  _ \   __\\   __\ \/ \/ /\__  \\_  __ \_/ __ \ 
#   \     /  |   |  /        (  <_> )  |   |  |  \     /  / __ \|  | \/\  ___/ 
#    \___/   |___| /_______  /\____/|__|   |__|   \/\_/  (____  /__|    \___  >
#                          \/                                 \/            \/ 
#                          
#     © 2023-2026 VI Software and contributors.
#     Portions © 2017-2026 Daniel D. Scalzi. Licensed under the MIT License.
#
#     License: GNU Affero General Public License v3.0 (AGPL-3.0)
#     https://www.gnu.org/licenses/agpl-3.0.en.html
#
#     This program is distributed in the hope that it will be useful, but WITHOUT 
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
#     FITNESS FOR A PARTICULAR PURPOSE. See the license for more details.
#
#     GitHub:  https://github.com/VI-Software
#     Website: https://visoftware.dev

[ejs.app]
title = "VI Software Launcher"
title_nightly = "VI Software Launcher Nightly"
title_canary = "VI Software Launcher Canary"
[ejs.landing]
websiteURL = "https://visoftware.dev"
mediaGitHubURL = "https://github.com/VI-Software"
mediaDiscordURL = "https://visoftware.dev/discord"
canaryWebsiteURL = "https://visoftware.dev/launcher"

[ejs.settings]
sourceGithubLink = "https://github.com/VI-Software/vis-launcher"
supportLink = "https://github.com/VI-Software/vis-launcher/issues"

[launcher]
guestModeEnabled = true
legacyLoginUIEnabled = false
modStoreEnabled = true