#
#    ____   ____.___    _________       _____  __                                 
# \   \ /   /|   |  /   _____/ _____/ ____\/  |___  _  _______ _______   ____  
#  \   Y   / |   |  \_____  \ /  _ \   __\\   __\ \/ \/ /\__  \\_  __ \_/ __ \ 
#  \     /  |   |  /        (  <_> )  |   |  |  \     /  / __ \|  | \/\  ___/ 
#   \___/   |___| /_______  /\____/|__|   |__|   \/\_/  (____  /__|    \___  >
#                         \/                                 \/            \/ 
#                         
#                         
#    Copyright 2024 (©) VI Software y contribuidores. Todos los derechos reservados.
#    
#    GitHub: https://github.com/VI-Software
#    Documentación: https://docs-vis.galnod.com/vi-software/vis-launcher
#    Web: https://visoftware.tech
#    Licencia del proyecto: https://github.com/VI-Software/vis-launcher/blob/main/LICENSE

[ejs.app]
title = "VI Software Launcher"
title_nightly = "VI Software Launcher Nightly"

[ejs.landing]
mediaGitHubURL = "https://github.com/VI-Software"
mediaDiscordURL = "https://visoftware.tech/discord"

[ejs.settings]
sourceGithubLink = "https://github.com/VI-Software/vis-launcher"
supportLink = "https://github.com/VI-Software/vis-launcher/issues"


[ejs.welcome]
welcomeHeader = "Welcome to VI Software Launcher"
welcomeDescription = 'This launcher was developed by the VI Software team to simplify modpack management in VIS experiences. By using this launcher, you agree to the <a style="color: purple;" href="https://docs.visoftwre.tech/vi-software/vis-launcher/privacy-policy">privacy policy</a> and <a href="https://docs.visoftware.tech/vi-software/vis-launcher/terms-of-service" style="color: purple;">terms of service</a> of VI Software.'
welcomeDescCTA = "Fun is just around the corner!"

